### ISSUE TITLE
Looks Different

### ISSUE THREAD

**Issue by gvoze32** [mireq/rEFInd-Catalina#1]
This is not a bug or request actually, but how can my rEFInd looks like yours? I mean the bottom menu order and that all white icons (mine have one yellow big icon). This is mine:

![image](https://user-images.githubusercontent.com/28755051/85340590-927d2280-b510-11ea-9ab4-3deadb227b31.png)

**Comment by gvoze32** [comment]
How can i achieve to look like yours?

**Comment by t3dium** [comment]
You can edit refind.conf in `/boot/efi/EFI/refind` and add `hideui hints` and `hideui label` to hide the text. 

As for that yellow icon, im assuming it was added to refind after this theme was creating as there's no themed icon for it, I've personally deleted that icon (called os_hidden.png), and then copied and renamed the themed help icon to replace that icon.

**Comment by mireq** [comment]
This is new icon in version 0.13 (func_hidden). It can be removed using showtools option.

New version of this theme has new icons, so you can upgrade this theme.
